`timescale 1ns/1ps

module alu_tb;

reg [3:0] A, B;
reg [2:0] sel;
wire [3:0] result;
wire carry;

alu uut (
    .A(A),
    .B(B),
    .sel(sel),
    .result(result),
    .carry(carry)
);

initial begin
    $display("A B sel | result carry");

    // ADD
    A = 4'b0101; B = 4'b0011; sel = 3'b000;
    #10;

    // SUB
    sel = 3'b001;
    #10;

    // AND
    sel = 3'b010;
    #10;

    // OR
    sel = 3'b011;
    #10;

    // NOT
    sel = 3'b100;
    #10;

    $finish;
end

initial begin
    $monitor("%b %b %b | %b %b", A, B, sel, result, carry);
end

endmodule